### ISSUE TITLE
Fatal error: Class not found

### ISSUE THREAD

**Issue by rcgit** [kemoycampbell/cpanelAPI#1]
I just ran `composer install`, then attempted to hit **test.php** and got this error:

Fatal error: Uncaught Error: Class 'hostjams\Cpanel\Config\Config' not foundin [...]/test.php:16 Stack trace: #0 {main} thrown in [...]/test.php on line 16

This error occurs on both Windows and Linux.

**Comment by kemoycampbell** [comment]
Hey, thanks for pointing this out. I have corrected the issue. Discard everything that you have and pull again. It should be working this time

**Comment by rcgit** [comment]
Yes! Working now. Thank you very much, Kemoy! And my pleasure reporting.

Would you like me to fix English spelling and grammar issues in the README?

**Comment by kemoycampbell** [comment]
go for it
