### ISSUE TITLE
cPanel login url redirect

### ISSUE THREAD

**Issue by yashodhank** [kemoycampbell/cpanelAPI#3]
Thank you so much for creating and sharing it.

I would like to know, is it possible to login to cPanel (web interface, single sign on) using only your library where we only have cPanel username and password? How does that work? Thanks

**Comment by kemoycampbell** [comment]
This is meant to interact with the Cpanel programmatically. If you want your users to login to a cpanel-like interface, you will have to develop such interface and call the api accordingly.
